import os
import joblib
import pandas as pd
import numpy as np
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

# --- CORS ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],    # すべてのドメインからのアクセスを許可
    allow_credentials=True,
    allow_methods=["*"],    # すべてのメソッド(POST, GETなど)を許可
    allow_headers=["*"],    # すべてのヘッダーを許可
)

# 1. Load the serialized artifacts (model, encoders, and feature names)
# These files were generated by the train.py script
model = joblib.load('model.pkl')
encoder = joblib.load('encoder.pkl')
scaler = joblib.load('scaler.pkl')
cat_cols = joblib.load('cat_cols.pkl')
num_cols = joblib.load('num_cols.pkl')

# Define the request schema for data validation
class PredictionRequest(BaseModel):
    input_category: str
    input_price: float
    input_brand: str
    input_department: str
    age: int
    gender: str
    country: str

@app.post("/predict")
def predict(request: PredictionRequest):
    # Convert incoming JSON request into a pandas DataFrame
    input_dict = request.model_dump()
    df_input = pd.DataFrame([input_dict])

    # 2. Execute preprocessing steps consistent with the training phase
    # Transform categorical features using the fitted OneHotEncoder
    X_cat = encoder.transform(df_input[cat_cols])
    # Standardize numerical features using the fitted Scaler
    X_num = scaler.transform(df_input[num_cols])
    # Horizontally stack both categorical and numerical features
    X_final = np.hstack([X_cat, X_num])

    # 3. Predict class probabilities
    # model.classes_ contains the list of all product categories
    probabilities = model.predict_proba(X_final)[0]
    class_names = model.classes_
    
    # Sort prediction results by probability in descending order
    results = sorted(zip(probabilities, class_names), reverse=True)

    # Get the top 2 candidates
    top1_prob, top1_cat = results[0]
    top2_prob, top2_cat = results[1]

    # 4. Custom Business Logic: Cross-sell Strategy
    # If the Top-1 prediction matches the current category, 
    # we recommend the Top-2 prediction to encourage cross-category purchases.
    final_category = top1_cat
    strategy = "top1"
    
    if top1_cat == request.input_category:
        final_category = top2_cat
        strategy = "top2 (cross-sell logic triggered)"

    return {
        "recommended_category": final_category,
        "strategy": strategy,
        "details": {
            "rank1": {"category": top1_cat, "prob": round(top1_prob, 4)},
            "rank2": {"category": top2_cat, "prob": round(top2_prob, 4)}
        }
    }

if __name__ == "__main__":
    import uvicorn
    # Use PORT environment variable for Cloud Run compatibility
    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)